### ISSUE TITLE
Not initializing

### ISSUE THREAD

**Issue by nmaxcom** [andreruffert/rangeslider.js#343]
I can't get this to work. Following the instructions to the letter I get this:

![image](https://user-images.githubusercontent.com/8936090/68071934-1e72ec00-fd80-11e9-9259-8972253d1539.png)

Reading on, there's a small link to a CodePen so I checked it out. On the CSS it says this:

```css
// Critical CSS to initialize rangeslider.js
// Needs to be defined otherwise the initialization will fail.
.rangeslider__handle {
  width: 42px;
  height: 42px;
}
```

Is this a joke? Is it really "**critical**" to "**initialize** rangeslider.js" and it's mentioned nowhere in the docs or the examples?
