### ISSUE TITLE
Color Range Slider

### ISSUE THREAD

**Issue by eduardo-veras** [andreruffert/rangeslider.js#349]
I searched for this a lot and didn't found any solutions.

So just to help others that may be looking for the same thing, I created a small function that checks the value of the slider compared to position on the range, and change the fill color during the slide.

```javascript
 function rangeColorSet(range) {
    var size = Math.abs(Math.ceil((range.max - range.min) / 10));
    var step = 0;
    for (var s = 0; s <= 9; s++) {
      $(range.$fill).removeClass("step" + s);
      var stepStart = (size * s) + range.min;
      var stepEnd = (size * (s + 1)) + range.min;
      if (range.value >= stepStart && range.value < stepEnd) {
        step = s;
      }
    }
    if (range.value == range.max) step = 9;

    $(range.$fill).addClass("step" + step);
  }
```
and should be called on `onInt` and `onSlide` events such:

```javascript
  $("...").rangeslider({
    polyfill: false,

    onInit: function() { rangeColorSet(this); },
    onSlide: function(position, value) { rangeColorSet(this); },
 
  });
```

The colors are defined on a CSS:
```css
.rangeslider__fill.step0 { background: #00c49f; }
.rangeslider__fill.step1 { background: #00c884; }
.rangeslider__fill.step2 { background: #57ca6a; }
.rangeslider__fill.step3 { background: #9ccc53; }
.rangeslider__fill.step4 { background: #d7cb43; }
.rangeslider__fill.step5 { background: #f4bc3b; }
.rangeslider__fill.step6 { background: #f59d37; }
.rangeslider__fill.step7 { background: #f77d36; }
.rangeslider__fill.step8 { background: #f95c39; }
.rangeslider__fill.step9 { background: #f8323e; }
```

You can check this working at:
https://codepen.io/wakkoedu/pen/MWwPOwN
